### PR TITLE
dilithium: do not use symlinks

### LINKED ISSUE #149: Dilithium build error
I'm trying to use this package and am receiving this error:

```
# github.com/cloudflare/circl/sign/dilithium/mode1
[CENSORED]/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20200826133834-bd706baae982/sign/dilithium/mode1/dilithium.go:33:16: undefined: internal.PublicKey
# github.com/cloudflare/circl/sign/dilithium/mode2
[CENSORED]/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20200826133834-bd706baae982/sign/dilithium/mode2/dilithium.go:33:16: undefined: internal.PublicKey
# github.com/cloudflare/circl/sign/dilithium/mode2aes
[CENSORED]/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20200826133834-bd706baae982/sign/dilithium/mode2aes/dilithium.go:33:16: undefined: internal.PublicKey
# github.com/cloudflare/circl/sign/dilithium/mode3aes
[CENSORED]/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20200826133834-bd706baae982/sign/dilithium/mode3aes/dilithium.go:33:16: undefined: internal.PublicKey
# github.com/cloudflare/circl/sign/dilithium/mode1aes
[CENSORED]/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20200826133834-bd706baae982/sign/dilithium/mode1aes/dilithium.go:33:16: undefined: internal.PublicKey
# github.com/cloudflare/circl/sign/dilithium/mode4
[CENSORED]/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20200826133834-bd706baae982/sign/dilithium/mode4/dilithium.go:33:16: undefined: internal.PublicKey
# github.com/cloudflare/circl/sign/dilithium/mode4aes
[CENSORED]/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20200826133834-bd706baae982/sign/dilithium/mode4aes/dilithium.go:33:16: undefined: internal.PublicKey
```

### PR DESCRIPTION
**Pull request by bwesterb**
Instead of symlinking into mode3, we'll let gen.go generate
the other modes' sourcefiles from mode3.

This is to fix issues encountered with Go modules and symlinks (#149).

Fixes #149

### CODE REVIEW

File: sign/dilithium/gen.go [hunk 1]
```diff
@@ -228,3 +232,85 @@ func generateModePackageFiles() {
 		}
 	}
 }
+
+// Copies mode3 source files to other modes
```
Comment (armfazh) [inline sign/dilithium/gen.go:236]: Why not to move everything to templates and generate from them the implementations.

Comment (bwesterb) [reply sign/dilithium/gen.go:236]: Because then it's easy to test changes by developing them in mode3 (without having to run go generate.)

**Review by armfazh — APPROVED** [review]
