### PR TITLE
ecc/bls12381: Ensures pairing operations don't overwrite their input

### LINKED ISSUE #493: In ecc/bls12381, Pairing operations seems racy
It seems there are internal functions in circl that are "racy", because they are passing arrays using pointers, reading from these arrays and writing to these same arrays, causing data races when multiple go routines are operating on the same points at the same time.

This was discovered in the drand/kyber repo, where we have recently accepted a PR to add circl support for BLS12-381, but sadly despite having a test for data races in pairings, we didn't catch it earlier. (we weren't using `-race` in CI by mistake).

To reproduce:
```
git clone https://github.com/drand/kyber.git
cd kyber
go test -race ./pairing/circl_bls12381/...
``` 

This should fail in the `TestRacePairings` test.

### PR DESCRIPTION
**Pull request by armfazh**
Issue: Pairing functions internally convert input points to affine, overwriting the input. This causes troubles in a multiple goroutine scenario.

Fix: Ensures pairing operations don't overwrite the input.
Added a test for checking input's integrity.

Fixes #493

### CODE REVIEW

File: ecc/bls12381/g1.go [hunk 1]
```diff
@@ -392,7 +392,8 @@ func G1Generator() *G1 {
 }
 
 // affinize converts an entire slice to affine at once
-func affinize(points []*G1) {
+func affinize(points []*G1) (out []G1) {
```
Comment (thibmeu) [inline ecc/bls12381/g1.go:395]: What about not declaring `out` as a return variable, but declaring it on the line below? My sense is there is one less allocation, and the code reads the same.
Another question is about returning `[] *G1`, but I understand motivations reason to stick to `[]G1`

**Review by thibmeu — APPROVED** [review]
Looks good. One minor nit on variable declaration.

Tests are passing locally as well.

File: ecc/bls12381/g1.go (hunk 1 above)
Comment (bwesterb) [reply ecc/bls12381/g1.go:395]: To avoid allocations you could pass it as an argument.

**Review by bwesterb — APPROVED** [review]

File: ecc/bls12381/g1.go (hunk 1 above)
Comment (armfazh) [reply ecc/bls12381/g1.go:395]: I've tried passing the `out` slice as a parameter, but still one allocation is needed.

File: ecc/bls12381/g1.go
[the remark this answers is not in the document]
Comment (armfazh) [reply ecc/bls12381/g1.go:1]: For points in G2, the Miller's loop only uses the points in read-only mode.
